In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('Resources/kyphosis.csv')

In [3]:
data.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [4]:
data.shape

(81, 4)

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     str
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), str(1)
memory usage: 3.2 KB

In [8]:
x = data.drop('Kyphosis', axis = 1)

In [10]:
x.head()

   Age  Number  Start
0   71       3      5
1  158       3     14
2  128       4      5
3    2       5      1
4    1       4     15

In [17]:
y = data.Kyphosis

In [18]:
y.head()

0     absent
1     absent
2    present
3     absent
4     absent
Name: Kyphosis, dtype: str

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [24]:
x_train.shape

(56, 3)

In [25]:
x_test.shape

(25, 3)